#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World" when queried
#++    at the root with a curl GET request.

# Install Nginx
apt-get update
apt-get -y install nginx

# Ensure Nginx is listening on port 80
sed -i 's/80 default_server/80 default_server; root \/usr\/share\/nginx\/html/' /etc/nginx/sites-available/default

# Reload Nginx configuration
service nginx reload

# Create index.html with "Hello World!" content
echo "Hello World!" > /usr/share/nginx/html/index.html

# Check if Nginx is running
if pgrep -x "nginx" >/dev/null
then
    echo "Nginx installed and configured successfully!"
else
    echo "Failed to install or configure Nginx!"
fi
